In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
dataset = pd.read_csv('zameen-updated.csv')

In [ ]:
dataset.head()

,property_id,location_id,page_url,property_type,price,location,city,province_name,latitude,longitude,baths,area,purpose,bedrooms,date_added,agency,agent,Area Type,Area Size,Area Category
0,237062,3325,https://www.zameen.com/Property/g_10_g_10_2_gr...,Flat,10000000,G-10,Islamabad,Islamabad Capital,33.679890,73.012640,2,4 Marla,For Sale,2,02-04-2019,NaN,NaN,Marla,4.0,0-5 Marla
1,346905,3236,https://www.zameen.com/Property/e_11_2_service...,Flat,6900000,E-11,Islamabad,Islamabad Capital,33.700993,72.971492,3,5.6 Marla,For Sale,3,05-04-2019,NaN,NaN,Marla,5.6,5-10 Marla
2,386513,764,https://www.zameen.com/Property/islamabad_g_15...,House,16500000,G-15,Islamabad,Islamabad Capital,33.631486,72.926559,6,8 Marla,For Sale,5,07-17-2019,NaN,NaN,Marla,8.0,5-10 Marla
3,656161,340,https://www.zameen.com/Property/islamabad_bani...,House,43500000,Bani Gala,Islamabad,Islamabad Capital,33.707573,73.151199,4,2 Kanal,For Sale,4,04-05-2019,NaN,NaN,Kanal,2.0,1-5 Kanal
4,841645,3226,https://www.zameen.com/Property/dha_valley_dha...,House,7000000,DHA Defence,Islamabad,Islamabad Capital,33.492591,73.301339,3,8 Marla,For Sale,3,07-10-2019,Easy Property,Muhammad Junaid Ceo Muhammad Shahid Director,Marla,8.0,5-10 Marla

In [ ]:
dataset.isnull().sum()

property_id          0
location_id          0
page_url             0
property_type        0
price                0
location             0
city                 0
province_name        0
latitude             0
longitude            0
baths                0
area                 0
purpose              0
bedrooms             0
date_added           0
agency           23873
agent            23873
Area Type            1
Area Size            1
Area Category        1
dtype: int64

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34332 entries, 0 to 34331
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_id    34332 non-null  int64
 1   location_id    34332 non-null  int64
 2   page_url       34332 non-null  object
 3   property_type  34332 non-null  object
 4   price          34332 non-null  int64
 5   location       34332 non-null  object
 6   city           34332 non-null  object
 7   province_name  34332 non-null  object
 8   latitude       34332 non-null  float64
 9   longitude      34332 non-null  float64
 10  baths          34332 non-null  int64
 11  area           34332 non-null  object
 12  purpose        34332 non-null  object
 13  bedrooms       34332 non-null  int64
 14  date_added     34332 non-null  object
 15  agency         10459 non-null  object
 16  agent          10459 non-null  object
 17  Area Type      34331 non-null  object
 18  Area Size      34331 non-null  float64
 19  Area Category  34331 non-null  object
dtypes: float64(3), int64(5), object(12)
memory usage: 5.2+ MB

In [ ]:
dataset.describe()

,property_id,location_id,price,latitude,longitude,baths,bedrooms,Area Size
count,3.433200e+04,34332.000000,3.433200e+04,34332.000000,34332.000000,34332.000000,34332.000000,34331.000000
mean,1.181434e+07,4280.186590,1.817733e+07,30.044938,71.329913,3.193580,3.315100,5.843241
std,2.108425e+06,3717.013623,3.794734e+07,3.836872,3.109220,2.228647,2.046183,5.161849
min,8.657500e+04,4.000000,1.000000e+00,11.052446,25.906027,0.000000,0.000000,0.000000
25%,1.056809e+07,1020.000000,1.800000e+05,24.938913,67.120412,2.000000,2.000000,3.000000
50%,1.232275e+07,3233.000000,8.000000e+06,31.471571,73.065770,3.000000,3.000000,5.000000
75%,1.345478e+07,7184.000000,1.900000e+07,33.569523,73.218810,5.000000,5.000000,8.000000
max,1.428912e+07,13769.000000,1.270000e+09,73.184088,80.161430,11.000000,18.000000,500.000000

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()
dataset["property_type"] = le.fit_transform(dataset["property_type"])

In [ ]:
dataset["purpose"] = le.fit_transform(dataset["purpose"])
dataset["Area Type"] = le.fit_transform(dataset["Area Type"])

In [ ]:
dataset.head()

,property_id,location_id,page_url,property_type,price,location,city,province_name,latitude,longitude,baths,area,purpose,bedrooms,date_added,agency,agent,Area Type,Area Size,Area Category
0,237062,3325,https://www.zameen.com/Property/g_10_g_10_2_gr...,1,10000000,G-10,Islamabad,Islamabad Capital,33.679890,73.012640,2,4 Marla,1,2,02-04-2019,NaN,NaN,1,4.0,0-5 Marla
1,346905,3236,https://www.zameen.com/Property/e_11_2_service...,1,6900000,E-11,Islamabad,Islamabad Capital,33.700993,72.971492,3,5.6 Marla,1,3,05-04-2019,NaN,NaN,1,5.6,5-10 Marla
2,386513,764,https://www.zameen.com/Property/islamabad_g_15...,2,16500000,G-15,Islamabad,Islamabad Capital,33.631486,72.926559,6,8 Marla,1,5,07-17-2019,NaN,NaN,1,8.0,5-10 Marla
3,656161,340,https://www.zameen.com/Property/islamabad_bani...,2,43500000,Bani Gala,Islamabad,Islamabad Capital,33.707573,73.151199,4,2 Kanal,1,4,04-05-2019,NaN,NaN,0,2.0,1-5 Kanal
4,841645,3226,https://www.zameen.com/Property/dha_valley_dha...,2,7000000,DHA Defence,Islamabad,Islamabad Capital,33.492591,73.301339,3,8 Marla,1,3,07-10-2019,Easy Property,Muhammad Junaid Ceo Muhammad Shahid Director,1,8.0,5-10 Marla

In [ ]:
sns.heatmap(dataset.corr(), annot=True)
plt.show()

ValueError: could not convert string to float: 'https://www.zameen.com/Property/g_10_g_10_2_ground_floor_corner_apartment_with_green_lawn_for_sale-237062-3325-1.html'

In [ ]:
x = dataset.iloc[:, :-1]
y = dataset.iloc["price"]

TypeError: Cannot index by location index with a non-integer key

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

NameError: name 'y' is not defined

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
rf = RandomForestRegressor(n_estimators=10)
rf.fit(x_train, y_train)

NameError: name 'x_train' is not defined